services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - habittracking_db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - habittrackingnetwork
    env_file: ./backend/.env

  backend:
    build:
      context: .
      target: dev_backend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/prisma:/app/backend/prisma
      - ./backend/src:/app/backend/src
    depends_on:
      - db
    networks:
      - habittrackingnetwork
    ports:
      - 3001:3001
    env_file: ./backend/.env

  frontend:
    build:
      context: .
      target: dev_frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    ports:
      - 3000:3000

volumes:
  habittracking_db:

networks:
  habittrackingnetwork: